[package]
name = "orca_whirlpools_utils_js_bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
orca_whirlpools_utils = { path = "../../rust-sdk/utils", features = ["wasm", "floats"] }

[profile.release]
opt-level = "s"
